timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4

# Check link anchors
include_fragments = true

# excluding links to pull requests and issues is done for performance
exclude = [
  "^http://localhost:16686/$",
  '^https://github.com/open-telemetry/opentelemetry-android/(issues|pull)/\d+$',
  "^https://maven-badges.sml.io/maven-central/io.opentelemetry.android/.*$",
  "^https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/.*$",
]
