name: PR build

on: pull_request

jobs:
  pr-checks:
    name: "pr-checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: run gradle
        run: ./gradlew check

  required-status-check:
    needs:
      - pr-checks
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.pr-checks.result != 'success'
        run: exit 1